version: "3"

services:
  # Postgres backend database
  database:
    image: postgres:13-alpine
    container_name: elemental_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  # NGINX Web Server
  web-server:
    image: nginx:alpine
    container_name: web-server
    depends_on:
      - node-server
    ports:
      - "${SERVER_PORT}:80"

  # Backend API Node.js server
  node-server:
    image: elemental_server:latest
    container_name: elemental_server
    build:
      context: ./server
    depends_on:
      - database
    volumes:
      - ./server:/app
